#pragma once
#include <iostream>
#include "../GLAD/glad.h"
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include "../Graphics/VertexArray.h"
#include <math.h>
#include "../vendor/SimplexNoise.h"
#include <cmath>
#include <filesystem>
#include <iostream>
#include <fstream>
#include "../vendor/stb_image.h"